### ISSUE TITLE
Bei leerem Bild und gesetztem "flexible"-Backendtheme kommt ein Fehler

### ISSUE THREAD

**Issue by Defcon0** [katgirl/contao-avatar#37]
Und zwar dieser hier:

Fatal error: Uncaught exception Exception with message Directory "system/themes/flexible/images/" is not a file thrown in system/modules/core/library/Contao/File.php on line 98
#0 system/modules/core/library/Contao/Image.php(825): Contao\File->__construct('system/themes/f...', true)
#1 system/modules/avatar/library/Avatar/AvatarFileUpload.php(185): Contao\Image::getHtml(NULL, '', 'class="gimage" ...')
#2 system/modules/core/library/Contao/Widget.php(689): KirstenRoschanski\Avatar\Widget\AvatarFileUpload->generate()
#3 system/modules/core/templates/backend/be_widget.html5(3): Contao\Widget->generateWithError(true)
#4 system/modules/core/library/Contao/BaseTemplate.php(92): include('/home/dennis/Ku...')
#5 system/modules/core/library/Contao/Widget.php(635): Contao\BaseTemplate->parse()
#6 system/modules/core/classes/DataContainer.php(540): Contao\Widget->parse()
#7 system/modules/core/drivers/DC_Table.php(1890): Contao\DataContainer->row('{personal_legen...')
#8 system/modules/core/classes/Backend.php(631): Contao\DC_Table->edit()
#9 system/modules/core/controllers/BackendMain.php(135): Contao\Backend->getBackendModule('member')
#10 contao/main.php(22): Contao\BackendMain->run()
#11 {main}

**Comment by yeli69** [comment]
Den Fehler gibt es auch mit Contao 3.4.4 noch.

**Comment by a-v-l** [comment]
…auch in Version 3.4.5

**Comment by katgirl** [comment]
auch noch im develop-zweig? sollte damit behoben sein https://github.com/katgirl/contao-avatar/commit/f7baf4015d03e0e47b683e90d3fa7b86b6c607f9

**Comment by a-v-l** [comment]
Sorry, ich hatte meinen lokalen Server nicht richtig konfiguriert…
