### ISSUE TITLE
Bild beim Upload verkleinern hat keinen Effekt (Bug in AvatarWidget.php)

### ISSUE THREAD

**Issue by philvdb** [katgirl/contao-avatar#38]
Bin jetzt nicht besonders tief in die Materie eingestiegen aber mein Setup ist folgendes: In den Contao-Einstellungen "Maximale Abmessungen" 150x150, Proportional. "Bild beim Upload verkleinern" ist an.

Das erwartete Verhalten: Bilder, die von der GDlib verarbeitet werden können werden im Avatar-Ordner auf maximal 150px in einer Dimension proportional verkleinert.

Tatsächlich: Das Bild bleibt in Originalgröße.

Das Problem: Meiner Meinung nach sind die drei Zeilen ab
https://github.com/katgirl/contao-avatar/blob/master/src/library/Avatar/AvatarWidget.php#L280

```php
$arrImageSize[0],
$arrImageSize[1],
$arrImageSize[2]
```

zu ersetzen durch

```php
$arrImage[0],
$arrImage[1],
$arrImage[2]
```

Zumindest funktioniert dann bei mir die Erweiterung wie erwartet - ein simpler Vertippsler also. Etwas merkwürdig, dass das jetzt erst auffällt? Wenn ich etwas grob missverstanden habe, gern Bescheid sagen. Ansonsten liefere ich nötigenfalls auch einen PR für die drei Zeilchen.

**Comment by philvdb** [comment]
So, der pull request ist da mit ein paar weiteren Bugfixes

**Comment by katgirl** [comment]
please send the pull request at develop

**Comment by katgirl** [comment]
https://github.com/katgirl/contao-avatar/commit/bdba2b48579cfc802841a0a504a1a1fa6b76bc7c
