### ISSUE TITLE
Mitglieder im Backend nicht aufrufbar

### ISSUE THREAD

**Issue by do-while** [katgirl/contao-avatar#43]
Hallo Kirsten,
In Contao 3.5 habe ich Probleme mit avatar beim Aufruf eines Mitglieds.
```php
Fatal error: Uncaught exception Exception with message Directory "system/themes/default/images/" is not a file thrown in system/modules/core/library/Contao/File.php on line 123
```
Nach einiger Suche habe ich die entsprechende Stelle in avatar/library/Avatar/AvatarFileUpload.php gefunden:
```php
    if(count($arrValues) === 0)
    {
      $objFile = \FilesModel::findByPath($GLOBALS['TL_CONFIG']['avatar_fallback_image']);    
      $strInfo = $objFile->path . ' <span class="tl_gray">(' . $this->getReadableSize($objFile->size) . ($objFile->isGdImage ? ', ' . $arrImage[0] . 'x' . $arrImage[1] . ' px' : '') . ')</span>';
      $arrValues[$objFile->uuid] = \Image::getHtml(\Image::get($objFile->path, $arrImage[0], $arrImage[1], $arrImage[2]), '', 'class="gimage" title="' . specialchars($strInfo) . '"');
    }
```
Bei falscher Angabe im avatar_fallback_image kommt die betreffende Fehlermeldung, weil getHtml() dann auf einen Fehler läuft. Leider sagt die Fehlermeldung nichts über die Ursache aus, so dass ich erstmal ratlos war.

Lösung:
```php
    if(count($arrValues) === 0)
    {
      $objFile = \FilesModel::findByPath($GLOBALS['TL_CONFIG']['avatar_fallback_image']);    
      if( $objFile != NULL ) {
        $strInfo = $objFile->path . ' <span class="tl_gray">(' . $this->getReadableSize($objFile->size) . ($objFile->isGdImage ? ', ' . $arrImage[0] . 'x' . $arrImage[1] . ' px' : '') . ')</span>';
        $arrValues[$objFile->uuid] = \Image::getHtml(\Image::get($objFile->path, $arrImage[0], $arrImage[1], $arrImage[2]), '', 'class="gimage" title="' . specialchars($strInfo) . '"');
      }
    }
```
Bei mir hat es geholfen, die Variable $objFile zu prüfen. Das Backend ist dann wieder funktionsfähig.

Gruß aus Berlin
Hagen

**Comment by do-while** [comment]
Nachtrag:
die Variable ist aber korrekt in den Einstellungen gesetzt:
$GLOBALS['TL_CONFIG']['avatar_fallback_image'] = 'f4f038ba-72fc-11e3-b45a-5e97873fb0c7';

Da scheint also noch etwas im Argen zu liegen. UUID nicht berücksichtigt?

**Comment by katgirl** [comment]
Kann das nicht reproduzieren
